# -*- coding: utf-8 -*-
"""Start

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1foFo9VkkidrY8KCqxRUiYsP4UXZbS-OF
"""

# M O D E L    B U I L D I N G
early_stop_loss = EarlyStopping(monitor='loss', patience=3, verbose=1)
early_stop_val_acc = EarlyStopping(monitor='val_accuracy', patience=3, verbose=1)
model_callbacks=[early_stop_loss, early_stop_val_acc]