# -*- coding: utf-8 -*-
"""Data_Augmentation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUqKPrbILOWQEYT-0Hj1tm8BiXo0VgX1
"""

!unzip "/content/Digital Naturalist Dataset.zip"
Archive:  /content/Digital Naturalist Dataset.zip
   creating: Digital Naturalist Dataset/
   creating: Digital Naturalist Dataset/Bird/
   creating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (1).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (10).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (11).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (2).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (3).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (4).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (5).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (6).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (7).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (8).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download (9).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/download.jpg  
 extracting: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/greatindianbustard-kRDC--621x414@LiveMint.webp  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (1).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (2).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (3).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (4).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (5).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (6).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (7).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images (8).jpg  
  inflating: Digital Naturalist Dataset/Bird/Great Indian Bustard Bird/images.jpg  
   creating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (1).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (12).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (2).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (3).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (4).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (5).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (6).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download (7).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/download.jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (1).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (10).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (11).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (2).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (3).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (4).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (5).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (6).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (7).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (8).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images (9).jpg  
  inflating: Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird/images.jpg  
   creating: Digital Naturalist Dataset/Flower/
   creating: Digital Naturalist Dataset/Flower/Corpse Flower/
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download (1).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download (11).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download (2).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download (3).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download (4).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download (5).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/download.jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (1).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (10).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (11).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (12).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (13).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (14).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (15).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (16).jpg  
 extracting: Digital Naturalist Dataset/Flower/Corpse Flower/images (17).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (2).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (3).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (4).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (5).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (6).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (7).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (8).jpg  
  inflating: Digital Naturalist Dataset/Flower/Corpse Flower/images (9).jpg  
 extracting: Digital Naturalist Dataset/Flower/Corpse Flower/images.jpg  
   creating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (1).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (10).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (2).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (3).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (4).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (5).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (6).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (7).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (8).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download (9).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/download.jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (1).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (10).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (11).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (12).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (2).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (3).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (4).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (5).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (6).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (7).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (8).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images (9).jpg  
  inflating: Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower/images.jpg  
   creating: Digital Naturalist Dataset/Mammal/
   creating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (1).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (2).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (3).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (4).jpg  
 extracting: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (5).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (6).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download (8).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/download.jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (1).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (10).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (11).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (12).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (13).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (14).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (15).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (16).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (2).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (3).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (4).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (5).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (6).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (7).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (8).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images (9).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Pangolin Mammal/images.jpg  
   creating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/download (1).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/download (2).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/download (3).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/download (7).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/download.jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (1).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (10).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (11).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (12).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (13).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (14).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (15).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (16).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (2).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (3).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (4).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (5).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (6).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (7).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (8).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images (9).jpg  
  inflating: Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal/images.jpg  
Importing Required Libraries

from keras.preprocessing.image import ImageDataGenerator
import cv2
from os import listdir
import time
Data Augment Function

def augment_data(file_dir, n_generated_samples, save_to_dir):
    data_gen = ImageDataGenerator(rotation_range=30, 
                                  width_shift_range=0.1,
                                  height_shift_range=0.15, 
                                  shear_range=0.25, 
                                  zoom_range = 0.2,
                                  horizontal_flip=True, 
                                  vertical_flip=False, 
                                  fill_mode='nearest',
                                  brightness_range=(0.5,1.2)
                                 )
    for filename in listdir(file_dir):
        image = cv2.imread(file_dir + '/' + filename)
        image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
        image = image.reshape((1,)+image.shape)
        save_prefix = 'aug_' + filename[:-4]    
        i=0
        for batch in data_gen.flow(x=image, batch_size=1, save_to_dir=save_to_dir,
                                   save_prefix=save_prefix, save_format='jpg'):
            i += 1
            if i > n_generated_samples:
                break
augmented_data_path = '/content/Augument Dataset'
augment_data(file_dir='/content/Digital Naturalist Dataset/Bird/Great Indian Bustard Bird', n_generated_samples=20, save_to_dir=augmented_data_path+'/GIB_AUG')
augment_data(file_dir='/content/Digital Naturalist Dataset/Bird/Spoon Billed Sandpiper Bird', n_generated_samples=20, save_to_dir=augmented_data_path+'/SPS_AUG')
augment_data(file_dir='/content/Digital Naturalist Dataset/Flower/Corpse Flower', n_generated_samples=20, save_to_dir=augmented_data_path+'/Corpse_AUG')
augment_data(file_dir='/content/Digital Naturalist Dataset/Flower/Lady Slipper Orchid Flower', n_generated_samples=20, save_to_dir=augmented_data_path+'/LS_Orchid_AUG')
augment_data(file_dir='/content/Digital Naturalist Dataset/Mammal/Pangolin Mammal', n_generated_samples=20, save_to_dir=augmented_data_path+'/LS_Pangolin_AUG')
augment_data(file_dir='/content/Digital Naturalist Dataset/Mammal/Senenca White Deer Mammal', n_generated_samples=20, save_to_dir=augmented_data_path+'/SW_D